plugins {
    id 'java'
    id 'application'
}

group = 'edu.bbte.kripto'
version = 'unspecified'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':common')
}

application {
    mainClass = 'edu/bbte/kripto/FakeServer'
}

tasks.register('runMutualAuthServer', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'edu.bbte.kripto.MutualAuthServer'
}